"""empty message

Revision ID: d97888a06478
Revises: 
Create Date: 2021-05-05 15:27:35.429783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97888a06478'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
